apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pinger
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
      - image: sickp/alpine-sshd:7.5.1
        command: ["/entrypoint.sh"]
        imagePullPolicy: IfNotPresent
        name: pinger
      restartPolicy: Always